<?php

/**
 * @package     Optimiseweb_Getclicky
 * @author      Kathir Vel (sid@optimiseweb.co.uk)
 * @copyright   Copyright (c) 2012 Optimiseweb Ltd
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$getClickyGoalEnabled = Mage::getStoreConfig('optimisewebgetclickyconfig/goal_cart_page/enabled');
$getClickyGoalId = Mage::getStoreConfig('optimisewebgetclickyconfig/goal_cart_page/goal_id');

/* Build the Code */
$js = "";
$js .= "<script type=\"text/javascript\">\n";
$js .= "var clicky_custom = clicky_custom || {};\n";
$js .= "clicky_custom.goal = {\n";
$js .= "id: \"" . $getClickyGoalId . "\"\n";
$js .= "};\n";
$js .= "</script>\n";

echo $js;