<?php

/**
 * @package     Optimiseweb_Getclicky
 * @author      Kathir Vel (sid@optimiseweb.co.uk)
 * @copyright   Copyright (c) 2012 Optimiseweb Ltd
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$getClickyGoalEnabled = Mage::getStoreConfig('optimisewebgetclickyconfig/goal_checkout_onepage_success/enabled');
$getClickyGoalId = Mage::getStoreConfig('optimisewebgetclickyconfig/goal_checkout_onepage_success/goal_id');
$getClickyGoalRevenue = Mage::getStoreConfig('optimisewebgetclickyconfig/goal_checkout_onepage_success/goal_revenue');

$getClickyGrandTotal = FALSE;

/* Get Order Grand Total */
if ($getClickyGoalRevenue)
{
  $getClickyOrder = Mage::getModel('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId());
  $getClickyGrandTotal = number_format($getClickyOrder->getGrandTotal(), 2, '.', '');
}

/* Build the Code */
$js = "";
$js .= "<script type=\"text/javascript\">\n";
$js .= "var clicky_custom = clicky_custom || {};\n";
$js .= "clicky_custom.goal = {\n";
if ($getClickyGoalRevenue AND $getClickyGrandTotal)
{
  $js .= "id: \"" . $getClickyGoalId . "\",\n";
  $js .= "revenue: \"" . $getClickyGrandTotal . "\"\n";
}
else
{
  $js .= "id: \"" . $getClickyGoalId . "\"\n";
}
$js .= "};\n";
$js .= "</script>\n";

echo $js;

/* $subTotal = $order->getSubtotal(); */
/* $order->getId(); */
/* $order->getIncrementId(); */